export const experienceData = [
  {
    title: "2025",
    position: "Full Stack Developer",
    company: "Solkuu — GrabLocal",
    date: "July 2025 – Jun 2026",
    location: "Bangalore",
    points: [
      "Core team member building GrabLocal — a curated marketplace and seller operating system connecting Indian consumers with premium homegrown brands, with same-day delivery, AI-powered recommendations, and a zero-commission seller model.",
      "Built and maintained the seller CRM frontend (React.js / Next.js) covering real-time order management, inventory tracking, payment reconciliation, and seller dashboards.",
      "Developed backend APIs and services with Node.js / Express.js for order processing, seller onboarding, inventory sync, and delivery management.",
      "Delivered the seller-facing React Native mobile application for on-the-go order and inventory management.",
      "Engineered an Electron.js desktop app that listens for incoming orders and automatically triggers receipt printing — enabling zero-touch, real-time order fulfillment.",
    ],
    tech: [
      "React.js",
      "Next.js",
      "Node.js",
      "Express.js",
      "React Native",
      "Electron.js",
      "TanStack Query",
      "MongoDB",
    ],
  },
  {
    title: "2024",
    position: "Software Developer",
    company: "AffWorld Technology",
    date: "May 2024 – May 2025",
    location: "Remote",
    points: [
      "Led development of a Real Estate CRM application (React Native / Expo) featuring property and vehicle listing, agent dashboards, and lead management tools.",
      "Engineered a scalable property rental platform with dynamic host/guest roles, file-based navigation via Expo Router, and secure online payments powered by Stripe.",
      "Built a client service and subscription app enabling users to browse plans, pay via Razorpay, and track project progress in real time.",
      "Implemented full authentication flows including session management and role-based access control.",
      "Collaborated with UI/UX designers on responsive, production-quality interfaces and ensured performance through code reviews and reusable components.",
    ],
    tech: ["React Native", "Expo", "Expo Router", "Stripe", "Razorpay", "TypeScript", "Auth", "UI/UX"],
  },
  {
    title: "2023",
    position: "MERN Stack Intern",
    company: "Brototype",
    date: "Aug 2023 – Apr 2024",
    location: "Bangalore",
    points: [
      "Built a Job Portal using MERN stack with microservices, clean architecture, and Docker & Kubernetes deployment.",
      "Integrated WebRTC for video calls and Socket.IO for real-time chat and notifications.",
      "Used RabbitMQ and gRPC for inter-service communication.",
      "Developed a complete eCommerce platform with Razorpay integration.",
      "Created mini-projects including Aadhar OCR and Netflix GPT: an AI-powered movie recommendation system.",
    ],
    tech: [
      "MongoDB",
      "Express",
      "React",
      "Node.js",
      "Docker",
      "Kubernetes",
      "WebRTC",
      "Socket.IO",
      "RabbitMQ",
      "gRPC",
      "Razorpay",
    ],
  },
]
